version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: clojure_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-hacking